# Generated by Django 5.0.1 on 2024-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
