# Generated by Django 5.0.1 on 2024-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qts',
            field=models.IntegerField(default=1),
        ),
    ]
