# Generated by Django 5.0.1 on 2024-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_product_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
